defaults: &defaults
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4

development:
  <<: *defaults
  host: localhost
  database: daily_pay_web
  username: root
  password:
  socket: /opt/homebrew/var/mysql/mysql.sock
  # You can also try /tmp/mysql.sock if the above doesn't work
